source 'https://github.com/CocoaPods/Specs.git'

target 'URBNShareKit', :exclusive => true do
  pod "URBNShareKit", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "URBNShareKit", :path => "../"

  
end
