osx_image: xcode7.3
language: objective-c
before_install: cd Example && rm -rf Pods && pod install && cd -
script:
- xcodebuild -workspace Example/URBNShareKit.xcworkspace -scheme URBNShareKit-Example clean build -destination "platform=iOS Simulator,name=iPhone 6,OS=latest" -destination-timeout 120 test